/**
 * Copyright COORDONNÉES 2025, 2026
 * SPDX-License-Identifier: MPL-2.0
 */

import type {
  GeoJSONSource,
  MapLayerEventType,
  MapLayerMouseEvent,
  MapLayerTouchEvent,
  Map as MapLibreMap,
  PopupOptions,
} from "maplibre-gl";
import { Popup } from "maplibre-gl";

import type { LayerMetadata } from "../types";

export type SetLayerPopupParams<T> = {
  layerId: string;
  trigger: keyof MapLayerEventType;
  renderCallback: (
    properties: T,
    layerMetadata: LayerMetadata,
  ) => HTMLElement | string;
  popupConfig?: PopupOptions;
  centerOnClick?: boolean;
};

export function makeSetLayerPopup({ map }: { map: MapLibreMap }) {
  /**
   * When setLayerPopup is called for a layer that has already
   * a click listener, we need to remove it before setting the new one
   */
  const popupRemovers: { [layerId: string]: () => void } = {};

  /**
   * Sets up a popup for a specific map layer, triggered by user interaction.
   * The popup content is generated by a callback function, which can return either
   * a string (HTML) or a DOM element.
   *
   * @template T - The type of the GeoJSON properties for the layer's features.
   * @param {Object} params - Parameters for setting up the popup.
   * @param {string} params.layerId - Name of the layer to attach the popup to.
   * @param {keyof MapLayerEventType} params.trigger - Type of event that triggers the popup (e.g., "click", "mouseenter").
   * @param {(properties: T) => HTMLElement | string} params.renderCallback - Callback that generates the popup content.
   *   Accepts the feature's properties and returns either a DOM element or a string of HTML.
   * @param {PopupOptions} [params.popupConfig] - Configuration for the popup (e.g., offset, anchor, className).
   * @param {boolean} params.centerOnClick - Whether to center the map after clicking on a popup symbol
   *
   * @example
   * // Example with HTML string
   * const renderPopup = (properties) => {
   *   return `<div class="popup-content">
   *     <h3>${properties.name}</h3>
   *     <p>Value: ${properties.value}</p>
   *   </div>`;
   * };
   *
   * mapApiRef.current.setLayerPopup({
   *   layerId: "my-layer-id",
   *   trigger: "click",
   *   renderCallback: renderPopup,
   *   popupConfig: {
   *     className: "custom-popup",
   *     closeButton: true,
   *     anchor: "bottom",
   *   },
   *   centerOnClick: true,
   * });
   *
   * @example
   * // Example with DOM element
   * const renderPopup = (properties) => {
   *   const div = document.createElement("div");
   *   div.innerHTML = `<h3>${properties.name}</h3><p>Value: ${properties.value}</p>`;
   *   return div;
   * };
   *
   * mapApiRef.current.setLayerPopup({
   *   layerId: "my-layer-id",
   *   trigger: "click",
   *   renderCallback: renderPopup,
   *   centerOnClick: true
   * });
   */
  function setLayerPopup<T extends Record<string, unknown>>({
    layerId,
    trigger,
    renderCallback,
    popupConfig,
    centerOnClick,
  }: SetLayerPopupParams<T>) {
    if (layerId in popupRemovers) {
      // Cleanup precedent trigger
      popupRemovers[layerId]?.();
      delete popupRemovers[layerId];
    }

    const onTrigger = async (ev: MapLayerMouseEvent | MapLayerTouchEvent) => {
      const geometry = ev.features?.[0]?.geometry;
      const eventProps = ev.features?.[0]?.properties;
      const id = ev.features?.[0]?.id;
      if (geometry && id && eventProps) {
        /** @todo Remove "any" casting  */
        const popup = new Popup(popupConfig).setLngLat(ev.lngLat);

        const source = map.getSource(layerId) as GeoJSONSource;
        const data = await source.getData();
        const properties = Object.assign(eventProps, {
          // MapLibre Events will remove any non-string and non-numeric properties from object definition
          // see https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/#querysourcefeatures
          // We want to add them back because we use complex object and potential null values
          // @ts-expect-error - MapLibre types are not accurate regarding feature properties
          ...data.features?.find((f) => Number(f.id) === Number(id))
            ?.properties,
        }) as T;

        const layerMetadata = map.getLayer(layerId)?.metadata as LayerMetadata;
        const content = renderCallback(properties as T, layerMetadata);
        if (typeof content === "string") {
          popup.setHTML(content);
        } else {
          popup.setDOMContent(content);
        }

        popup.addTo(map);
      }
    };

    // Add "trigger" listener
    map.on(trigger, layerId, onTrigger);

    // Add Mouse listeners
    const onMouseEnter = () => {
      map.getCanvas().style.cursor = "pointer";
    };
    const onMouseLeave = () => {
      map.getCanvas().style.cursor = "";
    };

    if (centerOnClick) {
      map.on("click", layerId, (e) => {
        const geometry = e?.features?.[0]?.geometry;
        if (geometry && "coordinates" in geometry) {
          const [coordo1, coordo2] = geometry.coordinates;
          if (
            coordo1 &&
            coordo2 &&
            typeof coordo1 === "number" &&
            typeof coordo2 === "number"
          ) {
            map.flyTo({
              center: [coordo1, coordo2],
            });
          }
        }
      });
    }

    if (trigger.includes("click")) {
      map.on("mouseenter", layerId, onMouseEnter);
      map.on("mouseleave", layerId, onMouseLeave);
    }

    // Define cleanup function
    const removeListeners = () => {
      map.off(trigger, layerId, onTrigger);

      if (trigger.includes("click")) {
        map.off("mouseenter", layerId, onMouseEnter);
        map.off("mouseleave", layerId, onMouseLeave);
      }
    };

    // Add cleanup function to regitry
    popupRemovers[layerId] = removeListeners;
  }

  return setLayerPopup;
}
