/**
 * Copyright COORDONNÉES 2025, 2026
 * SPDX-License-Identifier: MPL-2.0
 */

import type {
  MapLayerEventType,
  MapLayerMouseEvent,
  MapLayerTouchEvent,
  Map as MapLibreMap,
  PopupOptions,
} from "maplibre-gl";
import { Popup } from "maplibre-gl";

export type SetLayerPopupParams<T> = {
  layerId: string;
  trigger: keyof MapLayerEventType;
  renderCallback: (properties: T) => HTMLElement | string;
  popupConfig?: PopupOptions;
};

export function makeSetLayerPopup({ map }: { map: MapLibreMap }) {
  /**
   * When setLayerPopup is called for a layer that has already
   * a click listener, we need to remove it before setting the new one
   */
  const popupRemovers: { [layerId: string]: () => void } = {};

  /**
   * Sets up a popup for a specific map layer, triggered by user interaction.
   * The popup content is generated by a callback function, which can return either
   * a string (HTML) or a DOM element.
   *
   * @template T - The type of the GeoJSON properties for the layer's features.
   * @param {Object} params - Parameters for setting up the popup.
   * @param {string} params.layerId - Name of the layer to attach the popup to.
   * @param {keyof MapLayerEventType} params.trigger - Type of event that triggers the popup (e.g., "click", "mouseenter").
   * @param {(properties: T) => HTMLElement | string} params.renderCallback - Callback that generates the popup content.
   *   Accepts the feature's properties and returns either a DOM element or a string of HTML.
   * @param {PopupOptions} [params.popupConfig] - Configuration for the popup (e.g., offset, anchor, className).
   *
   * @example
   * // Example with HTML string
   * const renderPopup = (properties) => {
   *   return `<div class="popup-content">
   *     <h3>${properties.name}</h3>
   *     <p>Value: ${properties.value}</p>
   *   </div>`;
   * };
   *
   * mapApiRef.current.setLayerPopup({
   *   layerId: "my-layer-id",
   *   trigger: "click",
   *   renderCallback: renderPopup,
   *   popupConfig: {
   *     className: "custom-popup",
   *     closeButton: true,
   *     anchor: "bottom",
   *   }
   * });
   *
   * @example
   * // Example with DOM element
   * const renderPopup = (properties) => {
   *   const div = document.createElement("div");
   *   div.innerHTML = `<h3>${properties.name}</h3><p>Value: ${properties.value}</p>`;
   *   return div;
   * };
   *
   * mapApiRef.current.setLayerPopup({
   *   layerId: "my-layer-id",
   *   trigger: "click",
   *   renderCallback: renderPopup,
   * });
   */
  function setLayerPopup<T extends Record<string, unknown>>({
    layerId,
    trigger,
    renderCallback,
    popupConfig,
  }: SetLayerPopupParams<T>) {
    if (layerId in popupRemovers) {
      // Cleanup precedent trigger
      popupRemovers[layerId]?.();
      delete popupRemovers[layerId];
    }

    const onTrigger = (ev: MapLayerMouseEvent | MapLayerTouchEvent) => {
      const geometry = ev.features?.[0]?.geometry;
      const properties = ev.features?.[0]?.properties;
      if (geometry && properties) {
        /** @todo Remove "any" casting  */
        const popup = new Popup(popupConfig).setLngLat(ev.lngLat);

        const content = renderCallback(properties as T);
        if (typeof content === "string") {
          popup.setHTML(content);
        } else {
          popup.setDOMContent(content);
        }

        popup.addTo(map);
      }
    };

    // Add "trigger" listener
    map.on(trigger, layerId, onTrigger);

    // Add Mouse listeners
    const onMouseEnter = () => {
      map.getCanvas().style.cursor = "pointer";
    };
    const onMouseLeave = () => {
      map.getCanvas().style.cursor = "";
    };

    if (trigger.includes("click")) {
      map.on("mouseenter", layerId, onMouseEnter);
      map.on("mouseleave", layerId, onMouseLeave);
    }

    // Define cleanup function
    const removeListeners = () => {
      map.off(trigger, layerId, onTrigger);

      if (trigger.includes("click")) {
        map.off("mouseenter", layerId, onMouseEnter);
        map.off("mouseleave", layerId, onMouseLeave);
      }
    };

    // Add cleanup function to regitry
    popupRemovers[layerId] = removeListeners;
  }

  return setLayerPopup;
}
