import { Popup } from "maplibre-gl";
import type {
  Map as MapLibreMap,
  MapLayerEventType,
  PopupOptions,
  MapLayerMouseEvent,
  MapLayerTouchEvent,
} from "maplibre-gl";

export type SetLayerPopup<T> = {
  layerId: string;
  trigger: keyof MapLayerEventType;
  renderCallback: (properties: T) => HTMLElement | string;
  popupConfig?: PopupOptions;
};

export function makeSetLayerPopup(map: MapLibreMap) {
  /**
   * When setLayerPopup is called for a layer that has already
   * a click listener, we need to remove it before setting the new one
   */
  const popupRemovers: { [layerId: string]: () => void } = {};

  /**
   * Sets up a popup for a specific map layer, triggered by user interaction.
   * The popup content is generated by a callback function, which can return either
   * a string (HTML) or a DOM element (e.g., a React root).
   *
   * @template T - The type of the GeoJSON properties for the layer's features.
   * @param layerId Name of the layer to attach the popup to.
   * @param trigger Type of event that triggers the popup (e.g., "click", "mouseenter").
   * @param renderCallback  Callback that generates the popup content.
   *   Accepts the feature's properties and returns either a DOM element or a string of HTML.
   * @param popupConfig [Optional] Configuration for the popup (e.g., offset, anchor, className).
   *
   * @example
   * const renderPopup = (properties: MyDataType) => {
   *   const container = document.createElement("div");
   *   const root = createRoot(container);
   *   root.render(
   *     <MyReactPopupContent
   *       data={properties}
   *       onClose={() => root.unmount()}
   *     />
   *   );
   *   return container;
   * };
   *
   *  mapApiRef.current.setLayerPopup<MyDataType>({
   *    layerId: "my-layer-id",
   *    trigger: "click",
   *    renderCallback: renderPopup,
   *    popupConfig: {
   *      className: "bg-background/90 rounded-md",
   *      closeButton: false, // To self-manage the popup closing
   *      anchor: "center",
   *      ...
   *    }
   * }
   */
  function setLayerPopup<T extends Record<string, unknown>>({
    layerId,
    trigger,
    renderCallback,
    popupConfig,
  }: SetLayerPopup<T>) {
    if (layerId in popupRemovers) {
      // Cleanup precedent trigger
      popupRemovers[layerId]?.();
      delete popupRemovers[layerId];
    }

    const onTrigger = (ev: MapLayerMouseEvent | MapLayerTouchEvent) => {
      const geometry = ev.features?.[0]?.geometry;
      const properties = ev.features?.[0]?.properties;
      if (geometry && properties) {
        /** @todo Remove "any" casting  */
        const coordinates = (geometry as any).coordinates.slice();
        const popup = new Popup(popupConfig).setLngLat(coordinates);

        const content = renderCallback(properties as T);
        if (typeof content === "string") {
          popup.setHTML(content);
        } else {
          popup.setDOMContent(content);
        }

        popup.addTo(map);
      }
    };

    // Add "trigger" listener
    map.on(trigger, layerId, onTrigger);

    // Add Mouse listeners
    const onMouseEnter = () => {
      map.getCanvas().style.cursor = "pointer";
    };
    const onMouseLeave = () => {
      map.getCanvas().style.cursor = "";
    };

    if (trigger.includes("click")) {
      map.on("mouseenter", layerId, onMouseEnter);
      map.on("mouseleave", layerId, onMouseLeave);
    }

    // Define cleanup function
    const removeListeners = () => {
      map.off(trigger, layerId, onTrigger);

      if (trigger.includes("click")) {
        map.off("mouseenter", layerId, onMouseEnter);
        map.off("mouseleave", layerId, onMouseLeave);
      }
    };

    // Add cleanup function to regitry
    popupRemovers[layerId] = removeListeners;
  }

  return setLayerPopup;
}
