name: Run tests with uv

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    working-directory: subfolder

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        run: uv python install

      - name: Create virtual environment
        run: uv sync --locked

      - name: Install coordo-py
        run: uv pip install -e .

      - name: Run tests
        run: uv run test.py
